
const products = [
    {
      id: 1,
      title: "Apple",
      category: "Fruit",
      thumbnail: "A round fruit with a red, green, or yellow ",
      price: 89,
      rating: 5,
      discountPercentagePercentage: 0,
      images: [
        "../assets/images/products/1.png",
        "../assets/images/products/2.png",
        "../assets/images/products/3.png",
        "../assets/images/products/4.png",
      ],
    },
    {
      id: 2,
      title: "Banana",
      category: "Fruit",
      thumbnail:
        "A long, curved fruit with a yellow skin and sweet, creamy white flesh.",
      price: 71,
      rating: 5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/2.png",
        "../assets/images/products/3.png",
        "../assets/images/products/4.png",
        "../assets/images/products/5.png",
      ],
    },
    {
      id: 3,
      title: "Bread",
      category: "Bakery",
      thumbnail:
        "A staple food made from flour, water, and yeast, baked into a loaf.",
      price: 88,
      rating: 5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/3.png",
        "../assets/images/products/4.png",
        "../assets/images/products/5.png",
        "../assets/images/products/6.png",
      ],
    },
    {
      id: 4,
      title: "Broccoli",
      category: "Vegetable",
      thumbnail:
        "A green vegetable with a tree-like appearance, known for its high nutrient content.",
      price: 94,
      rating: 4.5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/4.png",
        "../assets/images/products/5.png",
        "../assets/images/products/6.png",
        "../assets/images/products/7.png",
      ],
    },
    {
      id: 5,
      title: "Carrot",
      category: "Vegetable",
      thumbnail:
        "A root vegetable with a crunchy texture and a sweet, earthy flavor.",
      price: 82,
      rating: 5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/5.png",
        "../assets/images/products/6.png",
        "../assets/images/products/7.png",
        "../assets/images/products/8.png",
      ],
    },
    {
      id: 6,
      title: "Cheese",
      category: "Dairy",
      thumbnail:
        "A dairy product made from milk, with a variety of textures and flavors.",
      price: 91,
      rating: 3.5,
      discountPercentage: 50,
      images: [
        "../assets/images/products/6.png",
        "../assets/images/products/7.png",
        "../assets/images/products/8.png",
        "../assets/images/products/9.png",
      ],
    },
    {
      id: 7,
      title: "Chicken",
      category: "Meat",
      thumbnail:
        "A type of poultry, often used as a source of protein in meals.",
      price: 68,
      rating: 3.5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/7.png",
        "../assets/images/products/8.png",
        "../assets/images/products/9.png",
        "../assets/images/products/10.png",
      ],
    },
    {
      id: 8,
      title: "Chocolate",
      category: "Dessert",
      thumbnail:
        "A sweet food made from cacao beans, used in a variety of desserts and confections.",
      price: 61,
      rating: 4.5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/8.png",
        "../assets/images/products/9.png",
        "../assets/images/products/10.png",
        "../assets/images/products/11.png",
      ],
    },
    {
      id: 9,
      title: "Coffee",
      category: "Dessert",
      thumbnail:
        "A dark, bitter beverage made from roasted coffee beans, typically used as a pick-me-up.",
      price: 98,
      rating: 5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/9.png",
        "../assets/images/products/10.png",
        "../assets/images/products/11.png",
        "../assets/images/products/12.png",
      ],
    },
    {
      id: 10,
      title: "Egg",
      category: "Dairy",
      thumbnail:
        "A oval-shaped reproductive body produced by birds, often used as a source of protein in meals.",
      price: 79,
      rating: 4.5,
      discountPercentage: 0,
      images: [
        "../assets/images/products/10.png",
        "../assets/images/products/11.png",
        "../assets/images/products/12.png",
        "../assets/images/products/13.png",
      ],
    },
    {
      id: 11,
      title: "Fish",
      category: "Meat",
      thumbnail:
        "A type of seafood, known for its omega-3 fatty acids and high protein content.",
      price: 89,
      rating: 3.5,
      discountPercentage: 50,
      images: [
        "../assets/images/products/11.png",
        "../assets/images/products/12.png",
        "../assets/images/products/13.png",
        "../assets/images/products/14.png",
      ],
    },
    {
      id: 12,
      title: "Grapes",
      category: "Fruit",
      thumbnail:
        "A small, sweet fruit that grows in clusters, often used in wine-making.",
      price: 61,
      rating: 4,
      discountPercentage: 20,
      images: [
        "../assets/images/products/12.png",
        "../assets/images/products/13.png",
        "../assets/images/products/14.png",
        "../assets/images/products/15.png",
      ],
    },
    {
      id: 13,
      title: "Hamburger",
      category: "Fast food",
      thumbnail:
        "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
      price: 87,
      rating: 5,
      discountPercentage: 0,
      images: [
        "../assets/images/products/13.png",
        "../assets/images/products/14.png",
        "../assets/images/products/15.png",
        "../assets/images/products/16.png",
      ],
    },
    {
      id: 14,
      title: "Hot dog",
      category: "Fast food",
      thumbnail:
        "A type of sausage served in a long roll, often used as a quick and convenient food.",
      price: 84,
      rating: 4.5,
      discountPercentage: 50,
      images: [
        "../assets/images/products/14.png",
        "../assets/images/products/15.png",
        "../assets/images/products/16.png",
        "../assets/images/products/17.png",
      ],
    },
    {
      id: 15,
      title: "Ice cream",
      category: "Dessert",
      thumbnail:
        "A frozen dessert made from cream, sugar, and flavorings, available in a variety of flavors.",
      price: 68,
      rating: 4.5,
      discountPercentage: 0,
      images: [
        "../assets/images/products/15.png",
        "../assets/images/products/16.png",
        "../assets/images/products/17.png",
        "../assets/images/products/18.png",
      ],
    },
    {
      id: 16,
      title: "Lemon",
      category: "Fruit",
      thumbnail:
        "A yellow citrus fruit with a tart, acidic flavor, often used in cooking and baking.",
      price: 74,
      rating: 3.5,
      discountPercentage: 0,
      images: [
        "../assets/images/products/16.png",
        "../assets/images/products/17.png",
        "../assets/images/products/18.png",
        "../assets/images/products/19.png",
      ],
    },
    {
      id: 17,
      title: "Eggs",
      category: "Dairy",
      thumbnail:
        "Eggs are oval-shaped reproductive structures produced by female birds and some reptiles.",
      price: 70,
      rating: 4.5,
      discountPercentage: 50,
      images: [
        "../assets/images/products/17.png",
        "../assets/images/products/18.png",
        "../assets/images/products/19.png",
        "../assets/images/products/20.png",
      ],
    },
    {
      id: 18,
      title: "Honey",
      category: "Dairy",
      thumbnail:
        "Honey is a sweet, sticky liquid made by bees from the nectar of flowers.",
      price: 87,
      rating: 4,
      discountPercentage: 0,
      images: [
        "../assets/images/products/18.png",
        "../assets/images/products/19.png",
        "../assets/images/products/20.png",
        "../assets/images/products/21.png",
      ],
    },
    {
      id: 19,
      title: "Ice Cream",
      category: "Dessert",
      thumbnail:
        "Ice cream is a frozen dessert made from cream, sugar, and flavorings.",
      price: 83,
      rating: 4.5,
      discountPercentage: 0,
      images: [
        "../assets/images/products/19.png",
        "../assets/images/products/20.png",
        "../assets/images/products/21.png",
        "../assets/images/products/22.png",
      ],
    },
    {
      id: 20,
      title: "Jelly",
      category: "Fruit",
      thumbnail:
        "Jelly is a sweet spread made from fruit juice and sugar, often used as a topping for toast or pastries.",
      price: 76,
      rating: 5,
      discountPercentage: 0,
      images: [
        "../assets/images/products/20.png",
        "../assets/images/products/21.png",
        "../assets/images/products/22.png",
        "../assets/images/products/23.png",
      ],
    },
    {
      id: 21,
      title: "Ketchup",
      category: "Dairy",
      thumbnail:
        "Ketchup is a tangy sauce made from tomatoes, vinegar, sugar, and spices.",
      price: 77,
      rating: 5,
      discountPercentage: 0,
      images: [
        "../assets/images/products/21.png",
        "../assets/images/products/22.png",
        "../assets/images/products/23.png",
        "../assets/images/products/24.png",
      ],
    },
    {
      id: 22,
      title: "Mango",
      category: "Fruit",
      thumbnail:
        "Mangoes are juicy, sweet tropical fruits with a fleshy interior and a large, oblong seed in the center.",
      price: 80,
      rating: 5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/22.png",
        "../assets/images/products/23.png",
        "../assets/images/products/24.png",
        "../assets/images/products/25.png",
      ],
    },
    {
      id: 23,
      title: "Noodles",
      category: "Meat",
      thumbnail:
        "Noodles are a type of pasta made from wheat flour and water, often used in Asian cuisine.",
      price: 93,
      rating: 3.5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/23.png",
        "../assets/images/products/24.png",
        "../assets/images/products/25.png",
        "../assets/images/products/26.png",
      ],
    },
    {
      id: 24,
      title: "Oatmeal",
      category: "Breakfast",
      thumbnail:
        "Oatmeal is a type of porridge made from oats that is often served for breakfast.",
      price: 94,
      rating: 4.5,
      discountPercentage: 0,
      images: [
        "../assets/images/products/24.png",
        "../assets/images/products/25.png",
        "../assets/images/products/26.png",
        "../assets/images/products/27.png",
      ],
    },
    {
      id: 25,
      title: "Bacon",
      category: "Breakfast",
      thumbnail:
        "Bacon is a popular breakfast food made from cured pork belly, it is newly delivered.",
      price: 71,
      rating: 3.5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/25.png",
        "../assets/images/products/26.png",
        "../assets/images/products/27.png",
        "../assets/images/products/28.png",
      ],
    },
    {
      id: 26,
      title: "Pancakes",
      category: "Breakfast",
      thumbnail:
        "Pancakes are a popular breakfast food made from flour, eggs, and milk.",
      price: 63,
      rating: 4,
      discountPercentage: 0,
      images: [
        "../assets/images/products/26.png",
        "../assets/images/products/27.png",
        "../assets/images/products/28.png",
        "../assets/images/products/29.png",
      ],
    },
    {
      id: 27,
      title: "Waffles",
      category: "Breakfast",
      thumbnail:
        "Waffles are a type of breakfast food made from batter cooked in a waffle iron.",
      price: 97,
      rating: 4.5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/27.png",
        "../assets/images/products/28.png",
        "../assets/images/products/29.png",
        "../assets/images/products/30.png",
      ],
    },
    {
      id: 28,
      title: "Fried Rice",
      category: "Lunch",
      thumbnail:
        "Fried Rice is a type of rice dish that is stir-fried in a pan with oil and other ingredients.",
      price: 81,
      rating: 4,
      discountPercentage: 20,
      images: [
        "../assets/images/products/28.png",
        "../assets/images/products/29.png",
        "../assets/images/products/30.png",
        "../assets/images/products/31.png",
      ],
    },
    {
      id: 29,
      title: "Spaghetti",
      category: "Lunch",
      thumbnail:
        "Spaghetti is a type of pasta made from wheat flour and water, usually served with sauce.",
      price: 96,
      rating: 3,
      discountPercentage: 50,
      images: [
        "../assets/images/products/29.png",
        "../assets/images/products/30.png",
        "../assets/images/products/31.png",
        "../assets/images/products/32.png",
      ],
    },
    {
      id: 30,
      title: "Pizza",
      category: "Lunch",
      thumbnail:
        "Pizza is a popular dish made from dough, sauce, cheese, and toppings.",
      price: 95,
      rating: 4,
      discountPercentage: 0,
      images: [
        "../assets/images/products/30.png",
        "../assets/images/products/31.png",
        "../assets/images/products/32.png",
        "../assets/images/products/33.png",
      ],
    },
    {
      id: 31,
      title: "Grilled Cheese",
      category: "Lunch",
      thumbnail:
        "A grilled cheese sandwich is a hot sandwich made from cheese and bread.",
      price: 100,
      rating: 5,
      discountPercentage: 50,
      images: [
        "../assets/images/products/31.png",
        "../assets/images/products/32.png",
        "../assets/images/products/33.png",
        "../assets/images/products/34.png",
      ],
    },
    {
      id: 32,
      title: "Steak",
      category: "Dinner",
      thumbnail:
        "Steak is a popular dinner dish made from a cut of beef that is usually grilled or pan-fried.",
      price: 63,
      rating: 4.5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/32.png",
        "../assets/images/products/33.png",
        "../assets/images/products/34.png",
        "../assets/images/products/35.png",
      ],
    },
    {
      id: 33,
      title: "Salmon",
      category: "Dinner",
      thumbnail:
        "Salmon is a type of fish that is often grilled or baked and served as a main course.",
      price: 82,
      rating: 4.5,
      discountPercentage: 20,
      images: [
        "../assets/images/products/33.png",
        "../assets/images/products/34.png",
        "../assets/images/products/35.png",
        "../assets/images/products/36.png",
      ],
    },
    {
      id: 34,
      title: "Chicken Alfredo",
      category: "Dinner",
      thumbnail:
        "Chicken Alfredo is a pasta dish made with chicken, alsjfkdlkasdfhlkjh.",
      price: 94,
      rating: 4,
      discountPercentage: 20,
      images: [
        "../assets/images/products/34.png",
        "../assets/images/products/35.png",
        "../assets/images/products/36.png",
        "../assets/images/products/1.png",
      ],
    },
    {
      id: 35,
      title: "Lasagna",
      category: "Dinner",
      thumbnail:
        "Lasagna is a type of pasta dish made with layers of pasta, sauce, cheese, and meat or vegetables.",
      price: 70,
      rating: 1,
      discountPercentage: 0,
      images: [
        "../assets/images/products/35.png",
        "../assets/images/products/36.png",
        "../assets/images/products/1.png",
        "../assets/images/products/2.png",
      ],
    },
    {
      id: 36,
      title: "Chocolate Chip Cookies",
      category: "Dessert",
      thumbnail:
        "Chocolate Chip Cookies are a type of cookie made from flour, sugar, butter, and chocolate chips.",
      price: 98,
      rating: 3.5,
      discountPercentage: 0,
      images: [
        "../assets/images/products/36.png",
        "../assets/images/products/1.png",
        "../assets/images/products/2.png",
        "../assets/images/products/3.png",
      ],
    },
  ];